name: Build Basic Tutorial Image

on:
  workflow_call:

jobs:
  build-base:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    env:
      GH_IMAGE: ghcr.io/mikewrock/test-bed:latest
      PUSH: ${{ (github.event_name != 'pull_request') && (github.repository == 'mikewrock/test-bed') }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Say Hello
        run: echo hello
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v23.1
        with:
          since_last_remote_commit: false
          files: |
            .docker/**
            README.md
      - name: Any changed
        if: steps.changed-files.outputs.any_changed == 'true'
        run: echo ${{ steps.changed-files.outputs.other_changed_files }}
      - name: Any changed
        if: steps.changed-files.outputs.any_changed == 'true'
        run: echo ${{ steps.changed-files.outputs.all_modified_files }}
      - name: Any unchanged
        if: steps.changed-files.outputs.any_changed != 'true'
        run: echo ${{ steps.changed-files.outputs.other_changed_files }}
      - name: Any unchanged
        if: steps.changed-files.outputs.any_changed != 'true'
        run: echo ${{ steps.changed-files.outputs.all_modified_files }}
      - name: Set up Docker Buildx
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: docker/setup-buildx-action@v2
      - name: Login to Github Container Registry
        if: steps.changed-files.outputs.any_changed == 'true' 
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Base Image
        uses: docker/build-push-action@v3
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          file: .docker/Dockerfile
          push: ${{ env.PUSH }}
          no-cache: false
          tags: |
            ${{ env.GH_IMAGE }}
