name: Build Secondary Images

on:
  workflow_call:

jobs:
  build-images:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    env:
      GH_IMAGE: ghcr.io/mikewrock/test-bed:secondary
      PUSH: ${{ (github.event_name != 'pull_request') && (github.repository == 'mikewrock/test-bed') }}
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Github Container Registry
        if: env.PUSH == 'true'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Hello World
        uses: docker/build-push-action@v3
        with:
          file: .docker/Dockerfile
          push: ${{ env.PUSH }}
          no-cache: false
          tags: |
            ${{ env.GH_IMAGE }}-image