name: Build Secondary Images

on:
  workflow_call:

jobs:
  build-images:
    strategy:
      fail-fast: false
      matrix:
        ROS_DISTRO: [humble, rolling]
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    env:
      GH_IMAGE: ghcr.io/mikewrock/test-bed:secondary
      PUSH: ${{ (github.event_name != 'pull_request') && (github.repository == 'mikewrock/test-bed') }}
      BASE_IMAGE_BRANCH: 
    steps:
      - name: Add -PR-<branch_name> to base image if this is a PR
        if: github.event_name == 'pull_request'
        run: |
          echo "BASE_IMAGE_BRANCH=-PR-${{ github.head_ref }}" >> $GITHUB_ENV
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Github Container Registry
        if: env.PUSH == 'true'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Hello World
        uses: docker/build-push-action@v3
        with:
          file: .docker/Dockerfile
          build-args: |
                ROS_DISTRO=${{ matrix.ROS_DISTRO }}
                BASE_BRANCH=${{ env.BASE_IMAGE_BRANCH }}
          target: hello_world_image
          push: ${{ env.PUSH }}
          no-cache: false
          tags: |
            ${{ env.GH_IMAGE }}-hello-world